name: Manual Trigger Test

on: 
  workflow_dispatch:

jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Create Java file
        run: |
          echo "public class Main { public static void main(String[] args) { System.out.println(\"Hello, World!\"); } }" > Main.java

      - name: Compile Java code
        run: javac Main.java

      - name: Run Java code
        run: java Main
